opencart:
  image: vimagick/opencart
  ports:
    - ${public_port}:80
  links:
    - mysql
  restart: always

mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=${db_root_password}
  restart: always
