.catalog:
  name: "Opencart"
  version: "v0.1"
  description: "Blog tool, publishing platform and CMS"
  uuid: Opencart-0
  minimum_rancher_version: v0.51.0
  questions:    
    - variable: public_port
      description: "public port to access the wordpress site"
      label: "Public Port"
      required: true
      default: "80"
      type: "int"


opencart:

mysql:
